name: UT_Music
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10  
  - flask=2.1.3  
  - filelock=3.7.1
  - numpy=1.24.0 
  - sqlalchemy=1.4.45 
  - werkzeug=2.2.2 
  - importlib-metadata=8.5.0
  - platformdirs=2.5.2
  - wtforms==2.2.1
  - pip==24.2
  - markupsafe==3.0.2
  - jinja2==3.1.4
  - itsdangerous==2.2.0
  - flask-wtf==1.2.1
  - zipp==3.21.0  
  - pydantic==2.10.5
  - pandas==2.2.3